language: cpp
os: osx

before_install:
  - wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -q conda-build anaconda-client
  - conda create -q -n test-environment python=3.7
  - source activate test-environment

script:
- conda build conda.recipe
- conda install --use-local ecell4_base
- anaconda -t $CONDA_UPLOAD_TOKEN upload /Users/travis/miniconda/conda-bld/osx-64/ecell4_base-v2.0.0b1-py37_*.tar.bz2
