language: cpp
os: osx

before_install:
  - wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda install -q conda-build
  - conda create -q -n test-environment python=3.7
  - source activate test-environment

script:
- conda build conda.recipe
- conda install --use-local ecell4_base
