sudo: required
dist: trusty
language: cpp
matrix:
  include:
  # - os: linux
  #   compiler: gcc
  #   language: python
  #   python: "2.7"
  #   env: TRAVIS_PYTHON_VERSION="2.7"
  # - os: linux
  #   compiler: clang
  #   language: python
  #   python: "2.7"
  #   env: TRAVIS_PYTHON_VERSION="2.7"
  - os: linux
    compiler: gcc
    language: python
    python: "3.5"
    env: TRAVIS_PYTHON_VERSION="3.5"
  - os: linux
    compiler: clang
    language: python
    python: "3.5"
    env: TRAVIS_PYTHON_VERSION="3.5"
  # - os: osx
  #   compiler: clang
  #   env: TRAVIS_PYTHON_VERSION="2.7"
  - os: osx
    compiler: clang
    env: TRAVIS_PYTHON_VERSION="3.6"
  - os: linux
    compiler: clang
    language: python
    python: "3.6"
    env: TRAVIS_PYTHON_VERSION="3.6"
  - os: linux
    compiler: clang
    language: python
    python: "3.7-dev"
    env: TRAVIS_PYTHON_VERSION="3.7"

addons:
  apt:
    sources:
    # - sourceline: 'ppa:mc3man/trusty-media'
    - ubuntu-toolchain-r-test
    packages:
    - clang
    - libboost-dev
    - libgsl0-dev
    - libhdf5-serial-dev
    # - python-setuptools
    # - python3-setuptools
    - python-dev
    - python3-dev
    - python3
    - python
    - wget
#    - ffmpeg

before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update;
    brew install gsl ffmpeg hdf5@1.8;
    brew info hdf5;
    cp /usr/local/Cellar/hdf5\@1.8/1.8.20_1/include/* /usr/local/include/;
    cp /usr/local/Cellar/hdf5\@1.8/1.8.20_1/lib/* /usr/local/lib/;
    if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
      brew install python2;
      which python2;
      python2 -V
      brew install freetype;
    fi;
    if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then
      brew upgrade python;
      which python3;
      python3 -V
      brew install freetype;
    fi;
  fi

- which python
- python -V

- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    mkdir ~/local;
    wget https://bootstrap.pypa.io/get-pip.py;
    python get-pip.py;
    python -m pip install -U cython numpy matplotlib jupyter;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    curl -O https://bootstrap.pypa.io/get-pip.py;
    if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
      python2 get-pip.py;
      python2 -m pip install -U cython numpy matplotlib jupyter;
    fi;
    if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then
      python3 get-pip.py;
      python3 -m pip install -U cython numpy matplotlib jupyter;
    fi;
  fi

script:
- set -ev
- PYTHON_EXECUTABLE=`which python`
- echo ${PYTHON_EXECUTABLE}
- ls -d /usr/include/python*
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
      export PYTHON_LIBRARY=/opt/python/2.7.14/lib;
      export PYTHON_INCLUDE_DIR=/opt/python/2.7.14/include/python2.7;
    fi;
    if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then
      export PYTHON_LIBRARY=/opt/python/3.5.5/lib;
      export PYTHON_INCLUDE_DIR=/opt/python/3.5.5/include/python3.5m;
    fi;
    echo ${PYTHON_INCLUDE_DIR};
  fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    bash -c 'wget https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.tar.gz && tar xf cmake-3.12.1-Linux-x86_64.tar.gz && ./cmake-3.12.1-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_PREFIX=~/local . && make && make test && make install';
    rm CMakeCache.txt;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
      sudo bash -c 'cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DPYTHON_EXECUTABLE:FILEPATH=python2 . && make && make test && make install';
    fi;
    if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then
      sudo bash -c 'cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DPYTHON_EXECUTABLE:FILEPATH=python3 . && make && ./ecell4/ode/tests/ODESimulator_test && make test && make install';
    fi;
    rm -f CMakeCache.txt;
  fi
- set +e

cache: false
notifications:
  webhooks:
    urls:
    - http://dev.e-cell.org/ecell-bot/travis/notification
  slack:
    secure: kCN8PCrinRfaDFKn93TMrYY5LberBt8GHDHOtSbR7B1Zmo9Pr/uHxxqoXlu1g9XYxgs2lud/AKo0gKMu8n+QHWeAXaOwe8GSccEqBdilXDVp4fzO96jT2R82RYljQ2wAR5ug1YIACRq06mtFn6U7GRZRnpRI4VsEUFLJPljZ+UM=
    slack: ecell-project:LvsPrINO4bNonZNTNw3IqMhV
