version: '{build}'
image: Visual Studio 2017
platform:
- x64

environment:
  matrix:
  - CONDA: 36-x64
  - CONDA: 37-x64

init:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- ps: $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"

install:
- ps: |
    git submodule update -q --init --recursive
    conda config --set always_yes yes --set changeps1 no
    conda update -q conda
    conda install -q conda-build anaconda-client conda-verify

build_script:
- cmd: |
    conda build conda.recipe
    move C:\Miniconda%CONDA%\conda-bld .
    if %APPVEYOR_REPO_TAG%==true anaconda -t %CONDA_UPLOAD_TOKEN% upload conda-bld\win-*\*.tar.bz2

artifacts:
  - path: 'conda-bld\win-*\*.tar.bz2'
