jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo hello from Windows
  - powershell: |
      Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      Get-Command conda.exe
      
