jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo hello from Linux
  - bash: |
      git submodule init && git submodule update
      apt-get update && apt-get install -y wget bzip2 python3-pip libgsl-dev libboost-dev cmake
      python3 -m pip install -U pip setuptools
      wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.4/src/hdf5-1.10.4.tar.bz2
      tar xf hdf5-1.10.4.tar.bz2 && cd hdf5-1.10.4
      ./configure --enable-cxx --prefix=/opt/hdf5 && make && make install
      cd ..
      export PATH=/opt/hdf5/bin:${PATH}
      export LD_LIBRARY_PATH=/opt/hdf5/lib:${LD_LIBRARY_PATH}
      export INCLUDE_PATH=/opt/hdf5/include:${INCLUDE_PATH}
      python3 setup.py build
      python3 setup.py install
      cd && pwd
      python3 -c "from ecell4_base import core"
