jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo hello from Linux
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: echo hello from macOS
  - bash: |
      brew update && brew upgrade cmake python
      brew install boost gsl hdf5
      /usr/local/bin/python3 -m pip install -U pip wheel delocate cython
      git clone git://github.com/ecell/ecell4-base && cd ecell4-base
      git submodule init && git submodule update && cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3 -DNO_SHARED:BOOL=1 . && make
      delocate-listdeps python/dist/*.whl
      delocate-wheel python/dist/*.whl
      delocate-listdeps python/dist/*.whl
      delocate-addplat --rm-orig -x 10_9 -x 10_10 python/dist/*.whl
  steps:
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'artifactName'
      targetPath: 'python/dist'
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: echo hello from Windows
