version: 2.1
executors:
  default:
    working_directory: ~/circle
    docker:
      - image: quay.io/pypa/manylinux2010_x86_64
    environment:
      ECELLVER: "2.0.0b3"
      CMAKEVER: "3.13.3"
      GSLVER: "2.4"
      BOOSTVER: "1.68.0"
      BOOSTFILE: "boost_1_68_0"
      HDF5VER: "1.10.4"

jobs:
  build:
    executor: default
    parameters:
      pyver:
        type: enum
        enum: ["cp35-cp35m", "cp36-cp36m", "cp37-cp37m"]
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          git submodule sync
          git submodule update --init --remote
      - run:
          name: Install Dependencies
          command: |
            set -x
            curl -O https://cmake.org/files/v3.13/cmake-$CMAKEVER.tar.gz
            curl -O ftp://ftp.gnu.org/gnu/gsl/gsl-$GSLVER.tar.gz
            curl -L -o $BOOSTFILE.tar.bz2 https://dl.bintray.com/boostorg/release/$BOOSTVER/source/$BOOSTFILE.tar.bz2
            curl -LO https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-$HDF5VER/src/hdf5-$HDF5VER.tar.bz2
            tar xf cmake-$CMAKEVER.tar.gz && tar xf gsl-$GSLVER.tar.gz && tar xf hdf5-$HDF5VER.tar.bz2 && tar xf $BOOSTFILE.tar.bz2
            cd cmake-$CMAKEVER && ./configure && make && make install
            cd ../gsl-$GSLVER && ./configure && make && make install
            cd ../hdf5-$HDF5VER && ./configure --prefix=/usr/local --enable-cxx && make && make install
            cd ~/circle
      - run:
          name: Install auditwheel from source
          command: |
            git clone https://github.com/pypa/auditwheel.git
            cd auditwheel && /opt/python/<< parameters.pyver >>/bin/python setup.py install
            /opt/python/<< parameters.pyver >>/bin/pip install pyelftools
      - run:
          name: Build E-Cell4
          command: |
            export BOOST_INCLUDEDIR=/root/circle/$BOOSTFILE
            /opt/python/<< parameters.pyver >>/bin/python setup.py bdist_wheel
            /opt/python/<< parameters.pyver >>/bin/auditwheel repair /root/circle/dist/ecell4_base-$ECELLVER-<< parameters.pyver >>-linux_x86_64.whl
      - store_artifacts:
          path: /root/circle/wheelhouse

workflows:
  version: 2
  build_wheels:
    jobs:
      - build:
          name: build_py35
          pyver: cp35-cp35m
      - build:
          name: build_py36
          pyver: cp36-cp36m
      - build:
          name: build_py37
          pyver: cp37-cp37m
