version: 2
jobs:
  build:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
    steps:
      - checkout
      - run: |
          pwd
          ls -al
          git submodule init
          git submodule update
