version: 2
jobs:
  build:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
    steps:
      - checkout
      - run: |
          git submodule sync
          git submodule update --init --remote
