package:
  name: ecell4_base
  version: {{ load_setup_py_data().version }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script_env:
    - CC
    - CXX

source:
  # git_url: ../
  path: ../

requirements:
  build:
    - {{ compiler('cxx') }} # [not osx]
    - cmake

  host:
    - python
    - hdf5
    - gsl
    - boost

  run:
    - python

test:
  imports:
    - ecell4_base.core
    - ecell4_base.bd
    - ecell4_base.egfrd
    - ecell4_base.gillespie
    - ecell4_base.meso
    - ecell4_base.ode
    - ecell4_base.sgfrd
    - ecell4_base.spatiocyte

about:
  summary: E-Cell4 project built with pybind11.
  license_file: LICENSE
