name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodule
      run: git submodule init && git submodule update
    - name: deps
      run: sudo apt-get update && sudo apt-get install -y wget bzip2 python3-pip libgsl-dev libboost-dev cmake && sudo python3 -m pip install -U pip setuptools
    - name: hdf5
      run: wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.4/src/hdf5-1.10.4.tar.bz2 && tar xf hdf5-1.10.4.tar.bz2 && cd hdf5-1.10.4 && ./configure --enable-cxx --prefix=/opt/hdf5 && make && sudo make install && cd ..
    - name: setuppy
      run: |
        export PATH=/opt/hdf5/bin:${PATH}
        export LIBRARY_PATH=/opt/hdf5/lib:${LIBRARY_PATH}
        export LD_LIBRARY_PATH=/opt/hdf5/lib:${LD_LIBRARY_PATH}
        export LD_RUN_PATH=/opt/hdf5/lib:${LD_RUN_PATH}
        export INCLUDE_PATH=/opt/hdf5/include:${INCLUDE_PATH}
        python3 setup.py build
        python3 setup.py test
        sudo python3 setup.py install
    - name: hoge
      run: pwd
